const mockResults = [
  {
    id: 1,
    itemName: 'asN 40',
    brandName: 'Pantoprazole',
    saltName: 'Pantoprazole Sodium',
    quantity: 500,
    price: 145.5,
    wholesaler: 'MediCare Distributors',
    area: 'Satellite',
    city: 'Ahmedabad',
    distance: 3.2,
    lastUpdate: '2026-01-01 09:30 AM',
    wholesalerDetails: {
      ownerName: 'Rajesh Kumar',
      mobile: '+91 98765 43210',
      email: 'contact@medicare.com',
      fullAddress:
        '45, Medical Complex, Satellite Road, Ahmedabad - 380015',
      rating: 4.8,
      totalProducts: 8500,
      establishedYear: 2010,
      verified: true,
      deliveryAvailable: true,
    },
  },
  {
    id: 2,
    itemName: 'laol 60',
    brandName: 'Pantocid',
    saltName: 'Pantoprazole Sodium',
    quantity: 1200,
    price: 142.0,
    wholesaler: 'HealthPlus Wholesale',
    area: 'Maninagar',
    city: 'Ahmedabad',
    distance: 5.8,
    lastUpdate: '2026-01-01 08:15 AM',
    wholesalerDetails: {
      ownerName: 'Amit Patel',
      mobile: '+91 98765 43211',
      email: 'info@healthplus.com',
      fullAddress:
        '128, Trade Center, Maninagar, Ahmedabad - 380008',
      rating: 4.6,
      totalProducts: 12000,
      establishedYear: 2008,
      verified: true,
      deliveryAvailable: true,
    },
  },
  {
    id: 3,
    itemName: 'jajam 50',
    brandName: 'Pantocid DSR',
    saltName: 'Pantoprazole + Domperidone',
    quantity: 350,
    price: 168.0,
    wholesaler: 'Prime Pharma Solutions',
    area: 'Vastrapur',
    city: 'Ahmedabad',
    distance: 8.5,
    lastUpdate: '2026-01-01 10:00 AM',
    wholesalerDetails: {
      ownerName: 'Priya Shah',
      mobile: '+91 98765 43212',
      email: 'sales@primepharma.com',
      fullAddress:
        '67, Pharma Hub, Vastrapur, Ahmedabad - 380054',
      rating: 4.9,
      totalProducts: 15000,
      establishedYear: 2005,
      verified: true,
      deliveryAvailable: false,
    },
  },
  {
    id: 4,
    itemName: 'ososl 40',
    brandName: 'Pantosec',
    saltName: 'Pantoprazole Sodium',
    quantity: 800,
    price: 139.5,
    wholesaler: 'Global Medical Traders',
    area: 'Navrangpura',
    city: 'Ahmedabad',
    distance: 12.3,
    lastUpdate: '2025-12-31 05:45 PM',
    wholesalerDetails: {
      ownerName: 'Suresh Mehta',
      mobile: '+91 98765 43213',
      email: 'contact@globalmed.com',
      fullAddress:
        '234, Commerce Plaza, Navrangpura, Ahmedabad - 380009',
      rating: 4.5,
      totalProducts: 9500,
      establishedYear: 2012,
      verified: true,
      deliveryAvailable: true,
    },
  },
];

export default mockResults;
